### ISSUE TITLE
OS - linux, qnap

### ISSUE THREAD

**Issue by dima-vy** [aviadlevy/ktuvitDownloader#2]
Should it work under linux OS? Tried to run it on qnap, this is the log:
[/share/CACHEDEV1_DATA/.qpkg/Entware-ng] # ktuvitDownloader -s /share/CACHEDEV1_DATA/test/
Please enter you username (email) for <ktuvit.com>: my_email@yahoo.com
Please enter your password:
Please enter your password again:
Traceback (most recent call last):
  File "/opt/bin/ktuvitDownloader", line 9, in <module>
    load_entry_point('ktuvitDownloader==2.0.4', 'console_scripts', 'ktuvitDownloader')()
  File "/opt/lib/python2.7/site-packages/ktuvitDownloader/__main__.py", line 128, in main
    downloader(base_dir, dest_dir, files, username, password, options.specific)
  File "/opt/lib/python2.7/site-packages/ktuvitDownloader/__main__.py", line 207, in downloader
    con = Connection(username, password, app_dir)
  File "/opt/lib/python2.7/site-packages/ktuvitDownloader/connection.py", line 88, in __init__
    self.driver = webdriver.Chrome(chrome_options=options)
  File "/opt/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/opt/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/opt/lib/python2.7/subprocess.py", line 390, in __init__
  File "/opt/lib/python2.7/subprocess.py", line 1024, in _execute_child
OSError: [Errno 8] Exec format error

Thank you

**Comment by aviadlevy** [comment]
didn't check it on linux.
this tool require selenium-driver to chrome. I'm not sure how well it's supported in linux.

for now, since Ktuvit website is currently not working, I'll not further investigate this. hope you understand
